### ISSUE TITLE
App - Blog Front

### ISSUE THREAD

**Issue by gabrielhcamacho** [gabrielhcamacho/appStartup#9]
Front da pagina do feed/ blog que serviria como tela apos o login.

Devera ter a funcionalidade do post para a publicação

**Comment by arielmmoreira** [comment]
o.0

**Comment by jose-pedro-marques** [comment]
oie

**Comment by Brunookamoto157** [comment]
;-;

**Comment by gabrielhcamacho** [comment]
![Feed.png](https://images.zenhubusercontent.com/60c258d150479622e8ff74ef/0e0c7cd4-ab61-4501-9d8a-ea0c016297eb)
